namespace WinShell;

internal static class SettingsCatalog
{
    public static readonly (string Name, string Uri)[] Pages =
    [
        ("Settings", "ms-settings:"),
        ("Display", "ms-settings:display"),
        ("Night light", "ms-settings:nightlight"),
        ("Graphics settings", "ms-settings:display-advancedgraphics"),
        ("Sound", "ms-settings:sound"),
        ("Volume mixer", "ms-settings:apps-volume"),
        ("Notifications", "ms-settings:notifications"),
        ("Focus assist", "ms-settings:quiethours"),
        ("Power & battery", "ms-settings:powersleep"),
        ("Storage", "ms-settings:storagesense"),
        ("Multitasking", "ms-settings:multitasking"),
        ("Clipboard", "ms-settings:clipboard"),
        ("Remote Desktop", "ms-settings:remotedesktop"),
        ("Projecting to this PC", "ms-settings:project"),
        ("About this PC", "ms-settings:about"),
        ("Bluetooth & devices", "ms-settings:bluetooth"),
        ("Connected devices", "ms-settings:connecteddevices"),
        ("Printers & scanners", "ms-settings:printers"),
        ("Mouse", "ms-settings:mousetouchpad"),
        ("Touchpad", "ms-settings:devices-touchpad"),
        ("Typing", "ms-settings:typing"),
        ("AutoPlay", "ms-settings:autoplay"),
        ("USB", "ms-settings:usb"),
        ("Network & internet", "ms-settings:network"),
        ("Wi-Fi", "ms-settings:network-wifi"),
        ("Ethernet", "ms-settings:network-ethernet"),
        ("VPN", "ms-settings:network-vpn"),
        ("Mobile hotspot", "ms-settings:network-mobilehotspot"),
        ("Airplane mode", "ms-settings:network-airplanemode"),
        ("Proxy", "ms-settings:network-proxy"),
        ("Personalization", "ms-settings:personalization"),
        ("Background", "ms-settings:personalization-background"),
        ("Colors", "ms-settings:colors"),
        ("Themes", "ms-settings:themes"),
        ("Lock screen", "ms-settings:lockscreen"),
        ("Taskbar", "ms-settings:taskbar"),
        ("Start", "ms-settings:personalization-start"),
        ("Fonts", "ms-settings:fonts"),
        ("Apps & features", "ms-settings:appsfeatures"),
        ("Installed apps", "ms-settings:appsfeatures"),
        ("Default apps", "ms-settings:defaultapps"),
        ("Startup apps", "ms-settings:startupapps"),
        ("Optional features", "ms-settings:optionalfeatures"),
        ("Your info", "ms-settings:yourinfo"),
        ("Sign-in options", "ms-settings:signinoptions"),
        ("Windows Update", "ms-settings:windowsupdate"),
        ("Date & time", "ms-settings:dateandtime"),
        ("Language & region", "ms-settings:regionlanguage"),
        ("Gaming", "ms-settings:gaming-gamebar"),
        ("Accessibility", "ms-settings:easeofaccess"),
        ("Privacy & security", "ms-settings:privacy"),
        ("Windows Security", "ms-settings:windowsdefender"),
        ("Recovery", "ms-settings:recovery"),
        ("Activation", "ms-settings:activation"),
        ("Troubleshoot", "ms-settings:troubleshoot"),
        ("For developers", "ms-settings:developers"),
    ];
}
